version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kampanyaradar_mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: e300386e
      MYSQL_DATABASE: kampanyaradar
      MYSQL_USER: kampanyaradar
      MYSQL_PASSWORD: appRadar3434**
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - kampanyaradar_network

  redis:
    image: redis:7-alpine
    container_name: kampanyaradar_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass "appRadar3434**"
    volumes:
      - redis_data:/data
    networks:
      - kampanyaradar_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kampanyaradar_backend
    restart: always
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=kampanyaradar
      - DB_USERNAME=kampanyaradar
      - DB_PASSWORD=appRadar3434**
      - REDIS_HOST=redis
      - REDIS_PASSWORD=appRadar3434**
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - kampanyaradar_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kampanyaradar_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
      - INTERNAL_API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    networks:
      - kampanyaradar_network

volumes:
  mysql_data:
  redis_data:

networks:
  kampanyaradar_network:
    driver: bridge